# Project information
site_name: 'WordHat'
site_description: 'WordHat is a Behat extension, providing WordPress-specific functionality for common testing scenarios specific to WordPress sites.'
site_author: 'Paul Gibbs'
site_url: 'https://wordhat.info/'
site_favicon: img/favicon.png
copyright: 'Copyright &copy; 2016-present, Paul Gibbs'

# Repository
repo_name: 'WordHat'
repo_url: 'https://github.com/paulgibbs/behat-wordpress-extension'
edit_uri: null

# Options
extra:
  logo: 'img/mark.svg'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif'
    code: 'Consolas, Monaco, monospace'
  social:
    - type: 'github'
      link: 'https://github.com/paulgibbs/behat-wordpress-extension'
    - type: 'twitter'
      link: 'https://twitter.com/pgibbs'
extra_css:
  - 'stylesheets/style.css'
use_directory_urls: false
google_analytics:
  - 'UA-88402256-1'
  - 'auto'
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - smarty
  - toc(permalink=true)
  - codehilite(guess_lang=false)

# Documentation and theme
theme: 'material'
theme_dir: "docs/theme"
pages:
  - Home: index.md
  - About:
    - Introduction: about.md
    - Credits: credits.md
    - License: license.md
  - Guide:
    - Requirements: requirements.md
    - Installation: installation.md
    #- Getting Started: installation.md
  - Configuration:
    - Settings: settings.md
    - Environment: environment-settings.md
  - Behat:
    - Drivers: drivers.md
    - Contexts: contexts.md
  - FAQs: faq.md
